//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhChiTietSP
    {
        public int MaAnh { get; set; }
        public string TenFileAnh { get; set; }
        public Nullable<int> MaSPTheoMau { get; set; }
    
        public virtual SPTheoMau SPTheoMau { get; set; }
    }
}
