//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSPBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietSPBan()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaChiTietSP { get; set; }
        public Nullable<double> KichCo { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public Nullable<int> MaSPTheoMau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual SPTheoMau SPTheoMau { get; set; }
    }
}
