//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiCuoiKy
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPTheoMaus = new HashSet<SPTheoMau>();
        }
    
        public int MaSanPham { get; set; }

        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Bắt buộc không được để trống")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "{0} phải từ {2} đến {1} ký tự")]
        public string TenSanPham { get; set; }

        [Display(Name = "Đơn giá bán nhỏ nhất")]
        public Nullable<decimal> DonGiaBanNhoNhat { get; set; }

        [Display(Name = "Trạng thái")]
        public string TrangThai { get; set; }

        [Display(Name = "Mô tả ngắn")]
        public string MoTaNgan { get; set; }

        [Display(Name = "Ảnh đại diện")]
        public string AnhDaiDien { get; set; }

        [Display(Name = "nổi bật")]
        public string NoiBat { get; set; }

        [Display(Name = "Mã phân loại phụ")]
        public Nullable<int> MaPhanLoaiPhu { get; set; }

        [Display(Name = "mã phân loại chính")]
        public Nullable<int> MaPhanLoai { get; set; }

        [Display(Name = "Giá nhập")]
        public Nullable<decimal> GiaNhap { get; set; }


        [Display(Name = "Phân loại chính")]
        public virtual PhanLoai PhanLoai { get; set; }

        [Display(Name = "Phân loại phụ")]
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }

        [Display(Name = "Sản phẩm theo màu")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPTheoMau> SPTheoMaus { get; set; }
    }
}
